SELECT 'requmgr_feature.sql: load data';
INSERT INTO requmgr_feature (id, f_id, name, featuregroup_id) VALUES (1, 'AssrQ',  'Assertion Query', 0);
INSERT INTO requmgr_feature (id, f_id, name, featuregroup_id) VALUES (2, 'Attr!',  'Attribute Query', 1);
INSERT INTO requmgr_feature (id, f_id, name, featuregroup_id) VALUES (3, 'ATeGov',  'Attribute Bundle/eGovToken', 2);
INSERT INTO requmgr_feature (id, f_id, name, featuregroup_id) VALUES (4, 'NameFmt',  'Attribute name formats', 2);
INSERT INTO requmgr_feature (id, f_id, name, featuregroup_id) VALUES (5, 'NamIdFmt',  'Name Identifier Formats', 2);
INSERT INTO requmgr_feature (id, f_id, name, featuregroup_id) VALUES (6, 'MsgFlow',  'Message Flow', 3);
INSERT INTO requmgr_feature (id, f_id, name, featuregroup_id) VALUES (7, 'AuthZ',  'MD authoritative', 4);
INSERT INTO requmgr_feature (id, f_id, name, featuregroup_id) VALUES (8, 'CertEx',  'MD Certificate Exchange', 4);
INSERT INTO requmgr_feature (id, f_id, name, featuregroup_id) VALUES (9, 'Cont',  'MD Contents', 4);
INSERT INTO requmgr_feature (id, f_id, name, featuregroup_id) VALUES (10, 'MsgFlow',  'Message Flow', 5);
INSERT INTO requmgr_feature (id, f_id, name, featuregroup_id) VALUES (11, 'NamIdMap',  'NameID Mapping', 6);
INSERT INTO requmgr_feature (id, f_id, name, featuregroup_id) VALUES (12, 'Connect',  'Connectivity', 7);
INSERT INTO requmgr_feature (id, f_id, name, featuregroup_id) VALUES (13, 'TLS',  'Endpoints MUST use TLS', 7);
INSERT INTO requmgr_feature (id, f_id, name, featuregroup_id) VALUES (14, 'MsgFlow',  'Message Flow', 8);
INSERT INTO requmgr_feature (id, f_id, name, featuregroup_id) VALUES (15, 'Requ',  'Request', 8);
INSERT INTO requmgr_feature (id, f_id, name, featuregroup_id) VALUES (16, 'Resp',  'Response', 8);
INSERT INTO requmgr_feature (id, f_id, name, featuregroup_id) VALUES (17, 'AuthnReq',  'Authn Request', 9);
INSERT INTO requmgr_feature (id, f_id, name, featuregroup_id) VALUES (18, 'Disco',  'IDP Discovery Service Protocol Profile', 9);
INSERT INTO requmgr_feature (id, f_id, name, featuregroup_id) VALUES (19, 'MsgFlow',  'Message Flow', 9);
INSERT INTO requmgr_feature (id, f_id, name, featuregroup_id) VALUES (20, 'NamIdFmt',  'Name Identifier Formats', 9);
INSERT INTO requmgr_feature (id, f_id, name, featuregroup_id) VALUES (21, 'Resp',  'Response', 9);
INSERT INTO requmgr_feature (id, f_id, name, featuregroup_id) VALUES (22, 'Session',  'Session', 9);
